[[main]]
  name = "About"
  url = "/about/basics/what-is-filecoin/"
  weight = 20

[[main]]
  name = "Intro"
  url = "/intro/intro-to-filecoin/what-is-filecoin/"
  weight = 30

[[main]]
  name = "Store"
  url = "/store/overview/start-storing/"
  weight = 60

[[main]]
  name = "Providers"
  url = "/storage-provider/basics/overview/"
  weight = 70

[[main]]
  name = "Smart contracts"
  url = "/developers/introduction/filecoin-and-ipfs"
  weight = 80
  identifier= "main-smart-contracts"

    [[main]]
      name = "Fundamentals"
      url = "/smart-contracts/fundamentals"
      weight = 10
      parent = "main-smart-contracts"

    [[main]]
      name = "Filecoin EVM runtime"
      url = "/smart-contracts/filecoin-evm-runtime"
      weight = 20
      parent = "main-smart-contracts"

    [[main]]
      name = "Ethereum wallet"
      url = "/smart-contracts/ethereum-wallet"
      weight = 30
      parent = "main-smart-contracts"

    [[main]]
      name = "Developing contracts"
      url = "/smart-contracts/developing-contracts"
      weight = 40
      parent = "main-smart-contracts"
    
    [[main]]
      name = "Testing contracts"
      url = "/smart-contracts/testing-contracts"
      weight = 50
      parent = "main-smart-contracts"

    [[main]]
      name = "Debugging contracts"
      url = "/smart-contracts/debugging-contracts"
      weight = 60
      parent = "main-smart-contracts"

[[main]]
  name = "Reference"
  url = "/reference/general/overview/"
  weight = 90

# docs.filecoin.io/about
# ----------------------
[[about]]
  name = "Basics"
  weight = 10
  identifier = "about-basics"
  url = "/about/basics"

[[about]]
  name = "Assets"
  weight = 20
  identifier = "about-assets"
  url = "/about/assets"

[[about]]
  name = "Project"
  weight = 30
  identifier = "about-project"
  url = "/about/project"

[[about]]
  name = "Community"
  weight = 40
  identifier = "about-community"
  url = "/about/community"

[[about]]
  name = "Contribute"
  weight = 50
  identifier = "about-contribute"
  url = "/about/contribute"
# ----------------------



# docs.filecoin.io/intro
# ----------------------
[[intro]]
  name = "Intro to Filecoin"
  weight = 10
  identifier = "intro-intro-to-filecoin"
  url = "/intro/intro-to-filecoin"
# ----------------------



# docs.filecoin.io/store
# ----------------------
[[store]]
  name = "Overview"
  weight = 10
  identifier = "store-overview"
  url = "/store/overview"

[[store]]
  name = "Tools"
  weight = 20
  identifier = "store-tools"
  url = "/store/tools"

[[store]]
  name = "Filecoin Plus"
  weight = 30
  identifier = "store-filecoin-plus"
  url = "/store/filecoin-plus"
# ----------------------



# docs.filecoin.io/providers
# ----------------------
[[storage-provider]]
  name = "Basics"
  weight = 10
  identifier = "providers-basics"
  url = "/storage-provider/basics"

[[storage-provider]]
  name = "Hardware"
  weight = 20
  identifier = "providers-hardware"
  url = "/storage-provider/hardware"

[[storage-provider]]
  name = "Rewards"
  weight = 30
  identifier = "providers-rewards"
  url = "/storage-provider/rewards"
# ----------------------



# docs.filecoin.io/smart-contracts
# ----------------------
[[smart-contracts]]
  name = "Fundamentals"
  weight = 10
  identifier = "smart-contracts-fundamentals"
  url = "/smart-contracts/Fundamentals"

[[smart-contracts]]
  name = "Filecoin EVM-runtime"
  weight = 20
  identifier = "smart-contracts-filecoin-evm-runtime"
  url = "/smart-contracts/filecoin-evm-runtime"

[[smart-contracts]]
  name = "Ethereum wallets"
  weight = 30
  identifier = "smart-contracts-ethereum-wallets"
  url = "/smart-contracts/ethereum-wallets"

[[smart-contracts]]
  name = "Developing contracts"
  weight = 40
  identifier = "smart-contracts-developing-contracts"
  url = "/smart-contracts/developing-contracts"

[[smart-contracts]]
  name = "Testing contracts"
  weight = 50
  identifier = "smart-contracts-testing-contracts"
  url = "/smart-contracts/testing-contracts"

[[smart-contracts]]
  name = "Debugging contracts"
  weight = 60
  identifier = "smart-contracts-debugging-contracts"
  url = "/smart-contracts/debugging-contracts"

# ----------------------



# docs.filecoin.io/reference
# ----------------------
[[reference]]
  name = "General"
  weight = 10
  identifier = "reference-general"
  url = "/reference/general"

[[reference]]
  name = "Exchanges"
  weight = 20
  identifier = "reference-exchanges"
  url = "/reference/exchanges"

[[reference]]
  name = "Built-in actors"
  weight = 30
  identifier = "reference-built-in-actors"
  url = "/reference/built-in-actors"

    [[built-in-actors]]
      name = "Protocol API"
      weight = 10
      identifier = "reference-built-in-actors-protocol-api"
      url = "/reference/built-in-actors/protocol-api"

    [[built-in-actors]]
      name = "Solidity API"
      weight = 20
      identifier = "reference-built-in-actors-solidity-api"
      url = "/reference/built-in-actors/solidity-api"

[[reference]]
  name = "External APIs"
  weight = 40
  identifier = "reference-external-apis"
  url = "/reference/external-apis"

[[reference]]
  name = "External APIs"
  weight = 40
  identifier = "reference-external-apis"
  url = "/reference/external-apis"

[[reference]]
  name = "JSON-RPC"
  weight = 50
  identifier = "reference-json-rpc"
  url = "/reference/json-rpc"





[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/filecoin-project/filecoin-docs"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/filecoin"
  weight = 20



# [[footer]]
#   name = "Privacy"
#   url = "/privacy"
#   weight = 10

# [[footer]]
#   name = "Terms"
#   url = "/terms"
#   weight = 20

# [[footer]]
#   name = "Contact"
#   url = "/contact"
#   weight = 30
