[[main]]
  name = "About"
  url = "/about/basics/what-is-filecoin/"
  weight = 20

[[main]]
  name = "Intro"
  url = "/intro/intro-to-filecoin/what-is-filecoin/"
  weight = 30

[[main]]
  name = "Store"
  url = "/store/overview/start-storing/"
  weight = 60

[[main]]
  name = "Providers"
  url = "/storage-provider/basics/overview/"
  weight = 70

[[main]]
  name = "Developers"
  url = "/developers/introduction/filecoin-and-ipfs"
  weight = 80
  identifier = "main-developers"

    [[main]]
      name = "Introduction"
      url = "/developers/introduction/overview"
      weight = 10
      parent = "main-developers"

    [[main]]
      name = "Infrastructure"
      url = "/developers/infrastructure/block-explorers"
      weight = 20
      parent = "main-developers"

    [[main]]
      name = "Smart contracts"
      url = "/developers/smart-contracts/filecoin-virtual-machine"
      weight = 30
      parent = "main-developers"

    [[main]]
      name = "Storage helpers"
      url = "/developers/storage-helpers/overview"
      weight = 40
      parent = "main-developers"

    [[main]]
      name = "JSON-RPC"
      url = "/developers/reference/json-rpc/introduction"
      weight = 50
      parent = "main-developers"
      
    [[main]]
      name = "Interplanetary Concensus"
      url = "/developers/ipc/introduction"
      weight = 60
      parent = "main-developers"

[[main]]
  name = "Reference"
  url = "/reference/reference/overview/"
  weight = 90



[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/filecoin-project/filecoin-docs"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/filecoin"
  weight = 20



# [[footer]]
#   name = "Privacy"
#   url = "/privacy"
#   weight = 10

# [[footer]]
#   name = "Terms"
#   url = "/terms"
#   weight = 20

# [[footer]]
#   name = "Contact"
#   url = "/contact"
#   weight = 30
